# fetch all tasks
GET http://localhost:3000/api/v1/user


POST http://localhost:3000/api/v1/auth/signup

Content-Type: application/json;

{
    "username" : "test",
    "email": "email@gmail.com",
    "password":"password",
}


POST http://localhost:3000/api/v1/auth/login

Content-Type: application/json;

{
    
    "email": "email@gmail.com",
    "password":"password",
}
